### ISSUE TITLE
Update to 1.15.1

### ISSUE THREAD

**Issue by LoneDev6** [dmulloy2/PacketWrapper#66]

**Comment by MiniDigger** [comment]
see #63

**Comment by LoneDev6** [comment]
Thanks, I hope it's not that hard for who knows this project well.
I would join the development but I have no knowledge on how is this project structured

**Comment by MiniDigger** [comment]
and thats the issue, nobody but aadnk does really :P

**Comment by Joeywp** [comment]
I believe it parses the wiki (wiki.vg/protocol) to read the field names and types, and tries to read the packet.class files bytecode to match those fields to the actual packet. Problem however, is that this technique doesn't seem to work anymore. One of the reasons is that the wiki has changed it's format a bit since the generator was created. Especially the nested tables make it hard to automatically parse and generate the packets. Some potential "fixes" could be:
- Asking the author(s) of the wiki.vg/protocol to make the tables more easily parsable by external tools, such as the packetwrapper generator, and after that update the generate accordingly
- Maybe the author of the wiki.vg/protocol actually has a tool which generates the wiki automatically, which could also be used to update packet wrapper automatically, but I think the author actually updates it manually
- Find a way to read the nested tables properly, which is kind of complicated as it's not just a nested table, but more like a merged table

After that, you probably also have to fix the packet.class parser. Fixing that probably requires you to be able to understand bytecode first, in order to understand what it's doing.

I tried to get it working myself some time ago, but as I just use a handful of packets, I just manually updated them.

**Comment by MiniDigger** [comment]
Wiki.vg is manually updated, yes. It's a community project, everybody can contribute.

I would vote for not reinventing the wheel, there are projects that already generate all needed data for us, for example minecraft-data: https://github.com/PrismarineJS/minecraft-data
That could be used as base going forward.

**Comment by dmulloy2** [comment]
https://github.com/dmulloy2/PacketWrapper/commit/5262e36c72b66a6b94eb97edc710094329a3ce5e
